name: Tests

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  GITHUB_ACCESS_TOKEN: ${{ github.token }}

jobs:
  check_token:
    runs-on: ubuntu-latest
    steps:
      - run: printenv
      - run: echo ${{ github.token }}
      - run: echo $GITHUB_ACCESS_TOKEN
      - run: echo $GITHUB_TOKEN

  swift_test:
    uses: bdrelling/ci/.github/workflows/swift_test.yml@main
    needs: [check_token]
    secrets: inherit
    with:
      scheme: GoatHerb
      # GitHub's API is rate limited and this SDK doesn't use authentication.
      # As such, we'll only test our core platforms (macOS and Linux, for Server-side Swift support).
      platforms: macOS Linux
      swift-versions: 5.5 5.6
