name: Tests

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  check_rate_limit:
    name: Check Rate Limit
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-11, macos-12]
    steps:
      - name: Check Rate Limit
        run: "curl -H 'UserAgent: GoatHerb' -L https://api.github.com/rate_limit"
  swift_test:
    uses: bdrelling/ci/.github/workflows/swift_test.yml@main
    secrets: inherit
    with:
      scheme: GoatHerb
      # GitHub's API is rate limited and this SDK doesn't use authentication.
      # As such, we'll only test our core platforms (macOS and Linux, for Server-side Swift support).
      platforms: macOS Linux
      swift-versions: 5.5 5.6
